### PR TITLE
Fix flaw where name registration was lost entirely on conflict

### PR DESCRIPTION
**Pull request by arjan**
The exiting of the loser process caused the name registration to be removed from the CRDT entirely.

### CODE REVIEW

**Comment by arjan** [comment]
Not sure that these failures are caused by my fix..

**Comment by derekkraan** [comment]
probably not. the tests are a little sensitive to time, not really sure how we could fix that, as we are testing an eventually consistent system ... :thinking:

**Comment by arjan** [comment]
wait I have a better solution than this, don't merge

**Comment by derekkraan** [comment]
I was about to write that I think this can be solved in a better way, but I'll wait to see what you come up with now ;)

**Comment by arjan** [comment]
`Process.unlink`

**Comment by derekkraan** [comment]
Ah, that's not what I had in mind. I think we need to clean up the ets tables properly when we detect that a pid loses. So in the `process_diff` function.

**Comment by arjan** [comment]
Yes, coming to realise that as well now

**Comment by arjan** [comment]
This should be better

**Comment by derekkraan** [comment]
I think we're really close. But we shouldn't delete the whole entry, just remove the key from its list of keys.

**Comment by arjan** [comment]
True

**Comment by arjan** [comment]
this patch should do the trick, I think

**Comment by derekkraan** [comment]
:ok_hand:

**Comment by arjan** [comment]
Awesome

**Pull request merged**
